LOAD DATA LOCAL INFILE 'student_data.txt' INTO TABLE Student
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'course_data.txt' INTO TABLE Course
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'tutorial_data.txt' INTO TABLE Tutorial
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n';
